#!/bin/bash
filename=screencast-$(date +%s)
ffmpeg -f x11grab -video_size 1920x1080 -framerate 60 -i $DISPLAY -f alsa \
 -i default -r 30 -s 1280x720 -c:v libx264 -preset:v veryfast -b:v 2000k -c:a libopus -b:a 128k \
 /tmp/$filename.mkv
ffmpeg -i /tmp/$filename.mkv -vcodec copy /home/ryan/Desktop/$filename.mp4
